[versions]
#noinspection UnusedVersionCatalogEntry
minSdk = "35"
#noinspection UnusedVersionCatalogEntry
targetSdk = "36"
#noinspection UnusedVersionCatalogEntry
appVersionCode = "1"
#noinspection UnusedVersionCatalogEntry
appVersionName = "1.0"

agp = "8.13.2"
kotlin = "2.2.21"
ksp = "2.2.21-RC2-2.0.4"

#camera = "1.5.1"

coreKtx = "1.17.0"
datastore = "1.1.7"
lifecycle = "2.9.4"
activityCompose = "1.11.0"
composeBom = "2025.11.00"
composeFoundation = "1.10.0-beta02"
appcompat = "1.7.1"
navigationCompose = "2.9.6"
foundation = "1.9.5"
miuix = "0.7.1"

biometric = "1.4.0-alpha04"

coil = "3.3.0"
#exoplayer = "1.8.0"
iconsExt = "1.7.8"

javaWebsocket = "1.6.0"
javaxServlet = "4.0.1"
jetty = "9.4.58.v20250814" # do not upgrade to higher versions, because javax.* is renamed to jakarta.* in later versions, but jupnp still uses the old namespace
protobuf = "4.33.0"
#shizuku = "13.1.5"
slf4jAndroid = "1.7.36"
slf4jApi = "2.0.17"
proto = "0.9.5"
jupnp = "3.0.3"
nanoHttpd = "2.3.1"
material = "1.14.0-alpha06"
rhino = "1.8.0"
kotlinSerialization = "1.9.0"

xposedApi = "82"
kavarefCore = "1.0.2"
kavarefExt = "1.0.1"
yukihookapi = "1.3.1"

#litert = "1.4.0"
#poseDetectionAccurate = "18.0.0-beta5"


[libraries]
androidx-core-ktx = { group = "androidx.core", name = "core-ktx", version.ref = "coreKtx" }
androidx-lifecycle = { module = "androidx.lifecycle:lifecycle-common", version.ref = "lifecycle" }
androidx-lifecycle-runtime-ktx = { group = "androidx.lifecycle", name = "lifecycle-runtime-ktx", version.ref = "lifecycle" }
androidx-lifecycle-viewmodel-ktx = { module = "androidx.lifecycle:lifecycle-viewmodel-ktx", version.ref = "lifecycle" }
androidx-lifecycle-viewmodel-compose = { module = "androidx.lifecycle:lifecycle-viewmodel-compose", version.ref = "lifecycle" }
androidx-activity-compose = { group = "androidx.activity", name = "activity-compose", version.ref = "activityCompose" }
androidx-compose-bom = { group = "androidx.compose", name = "compose-bom", version.ref = "composeBom" }
androidx-compose-foundation = { module = "androidx.compose.foundation:foundation", version.ref = "composeFoundation" }
android-material = { module = "com.google.android.material:material", version.ref = "material" }
androidx-material3 = { group = "androidx.compose.material3", name = "material3" }
androidx-ui = { group = "androidx.compose.ui", name = "ui" }
androidx-ui-graphics = { group = "androidx.compose.ui", name = "ui-graphics" }
androidx-ui-tooling = { group = "androidx.compose.ui", name = "ui-tooling" }
androidx-ui-tooling-preview = { group = "androidx.compose.ui", name = "ui-tooling-preview" }
androidx-appcompat = { group = "androidx.appcompat", name = "appcompat", version.ref = "appcompat" }
androidx-navigation-compose = { group = "androidx.navigation", name = "navigation-compose", version.ref = "navigationCompose" }
androidx-navigation-runtime-android = { group = "androidx.navigation", name = "navigation-runtime-android", version.ref = "navigationCompose" }
androidx-compose-material-icons-core = { module = "androidx.compose.material:material-icons-extended", version.ref = "iconsExt" }
androidx-foundation = { group = "androidx.compose.foundation", name = "foundation", version.ref = "foundation" }

androidx-datastore-core = { module = "androidx.datastore:datastore-core", version.ref = "datastore" }
androidx-datastore-preferences = { module = "androidx.datastore:datastore-preferences", version.ref = "datastore" }

androidx-biometric = { module = "androidx.biometric:biometric", version.ref = "biometric" }

#androidx-media3-ui = { module = "androidx.media3:media3-ui", version.ref = "exoplayer" }
#androidx-media3-ui-compose = { module = "androidx.media3:media3-ui-compose", version.ref = "exoplayer" }
#androidx-media3-exoplayer = { module = "androidx.media3:media3-exoplayer", version.ref = "exoplayer" }
#androidx-media3-exoplayer-dash = { module = "androidx.media3:media3-exoplayer-dash", version.ref = "exoplayer" }

#androidx-camera-extensions = { module = "androidx.camera:camera-extensions", version.ref = "camera" }
#androidx-camera-view = { module = "androidx.camera:camera-view", version.ref = "camera" }
#androidx-camera-lifecycle = { module = "androidx.camera:camera-lifecycle", version.ref = "camera" }
#androidx-camera-camera2 = { module = "androidx.camera:camera-camera2", version.ref = "camera" }
#androidx-camera-core = { module = "androidx.camera:camera-core", version.ref = "camera" }

miuix = { module = "top.yukonga.miuix.kmp:miuix", version.ref = "miuix" }

coil-compose = { module = "io.coil-kt.coil3:coil-compose", version.ref = "coil" }
coil-network-okhttp = { module = "io.coil-kt.coil3:coil-network-okhttp", version.ref = "coil" }

kotlin-reflect = { module = "org.jetbrains.kotlin:kotlin-reflect" }

java-websocket = { module = "org.java-websocket:Java-WebSocket", version.ref = "javaWebsocket" }

javax-servlet-api = { module = "javax.servlet:javax.servlet-api", version.ref = "javaxServlet" }
jetty-client = { module = "org.eclipse.jetty:jetty-client", version.ref = "jetty" }
jetty-server = { module = "org.eclipse.jetty:jetty-server", version.ref = "jetty" }
jetty-servlet = { module = "org.eclipse.jetty:jetty-servlet", version.ref = "jetty" }
jupnp = { group = "org.jupnp", name = "org.jupnp", version.ref = "jupnp" }
jupnp-android = { group = "org.jupnp", name = "org.jupnp.android", version.ref = "jupnp" }

protobuf-javalite = { module = "com.google.protobuf:protobuf-javalite", version.ref = "protobuf" }

slf4j-android = { module = "org.slf4j:slf4j-android", version.ref = "slf4jAndroid" }
slf4j-api = { module = "org.slf4j:slf4j-api", version.ref = "slf4jApi" }

#shizuku-api = { module = "dev.rikka.shizuku:api", version.ref = "shizuku" }
#shizuku-provider = { module = "dev.rikka.shizuku:provider", version.ref = "shizuku" }

nanoHttpd = { group = "org.nanohttpd", name = "nanohttpd", version.ref = "nanoHttpd" }

rhino = { module = "org.mozilla:rhino", version.ref = "rhino" }

xposed-api = { module = "de.robv.android.xposed:api", version.ref = "xposedApi" }
yukihookapi-api = { module = "com.highcapable.yukihookapi:api", version.ref = "yukihookapi" }
yukihookapi-ksp-xposed = { module = "com.highcapable.yukihookapi:ksp-xposed", version.ref = "yukihookapi" }
kavaref-core = { module = "com.highcapable.kavaref:kavaref-core", version.ref = "kavarefCore" }
kavaref-extension = { module = "com.highcapable.kavaref:kavaref-extension", version.ref = "kavarefExt" }

kotlin-serialization-json = { module = "org.jetbrains.kotlinx:kotlinx-serialization-json", version.ref = "kotlinSerialization" }

#litert = { module = "com.google.ai.edge.litert:litert", version.ref = "litert" }
#litert-metadata = { module = "com.google.ai.edge.litert:litert-metadata", version.ref = "litert" }
#litert-support = { module = "com.google.ai.edge.litert:litert-support", version.ref = "litert" }
#litert-gpu = { module = "com.google.ai.edge.litert:litert-gpu", version.ref = "litert" }
#pose-detection-accurate = { module = "com.google.mlkit:pose-detection-accurate", version.ref = "poseDetectionAccurate" }

[plugins]
android-application = { id = "com.android.application", version.ref = "agp" }
kotlin-android = { id = "org.jetbrains.kotlin.android", version.ref = "kotlin" }
kotlin-compose = { id = "org.jetbrains.kotlin.plugin.compose", version.ref = "kotlin" }
google-devtools-ksp = { id = "com.google.devtools.ksp", version.ref = "ksp" }
google-protobuf = { id = "com.google.protobuf", version.ref = "proto" }
kotlin-parcelize = { id = "kotlin-parcelize" }
